// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local file
config({ path: ".env.local" });

const prismaDatabaseUrl = process.env.PRISMA_DATABASE_URL;
const databaseUrl =
  process.env.DATABASE_URL ||
  process.env.POSTGRES_URL ||
  (prismaDatabaseUrl?.startsWith("postgres://") ? prismaDatabaseUrl : undefined);

// Keep Prisma CLI happy when providers expose POSTGRES_URL instead of DATABASE_URL.
if (!process.env.DATABASE_URL && databaseUrl) {
  process.env.DATABASE_URL = databaseUrl;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl || "",
  },
});
