import type { Metadata } from "next";
import BlobFollower from "./components/BlobFollower";
import { BlobHoverProvider } from "./components/BlobHoverContext";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <BlobHoverProvider>
          {children}
          <BlobFollower />
        </BlobHoverProvider>
      </body>
    </html>
  );
}
